server:
  shutdown: "graceful"

spring:
  lifecycle:
    timeout-per-shutdown-phase: "20s"

camel:
  health:
    enabled: true
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

management:
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          include:
            - camelHealth
            # zeebeClient will not get included in the liveness state
        readiness:
          include:
            - camelHealth
            - zeebeClient

baasflow:
  commons:
    events:
      audit:
        kafka:
          brokers: ${COMMONS_EVENTS_AUDIT_KAFKA_BROKERS}
          topic: ${COMMONS_EVENTS_AUDIT_KAFKA_TOPIC}

dfspids: "DFSPID"

fineract:
  api-url: ${FINERACT_URL}
  datatable-query-api: "/datatables/dt_client_account_mapping/query"
  column-filter: "iban"
  result-columns: "conversion_account_id,disposal_account_id,internal_account_id"
  internal-id-column: "internal_account_id"
  incoming-money-api: "/savingsaccounts/"
  locale: "en"

zeebe:
  client:
    worker:
      max-jobs-active: 100
      threads: 100

ams:
  local:
    server-cert-check: false
    enabled: false