camel:
  health:
    enabled: true
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

management:
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          include:
            - camelHealth
            # zeebeClient will not get included in the liveness state
        readiness:
          include:
            - camelHealth
            - zeebeClient

dfspids: "DFSPID"

fineract:
  api-url: ${FINERACT_URL}
  datatable-query-api: "/datatables/account_mapping/query"
  column-filter: "iban"
  result-columns: "conversion_account_id,disposal_account_id,internal_account_id"
  internal-id-column: "internal_account_id"
  incoming-money-api: "/savingsaccounts/"
  locale: "en"

zeebe:
  client:
    max-execution-threads: 1000
    evenly-allocated-max-jobs: 1000
    worker:
      max-jobs-active: 32
      threads: 5
#    max-execution-threads: 100
#    number-of-workers: 8
#    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "camunda8-zeebe-gateway.binx-dev:26500"

ams:
  local:
    server-cert-check: false
    enabled: false

