camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

dfspids: "DFSPID"

zeebe:
  broker:
    contactpoint: "ph-ee-zeebe:26500"

ams:
  local:
    enabled: true
    version: cn
    keystore-path: keystore.jks
    keystore-password: openmf
    interop:
      host: http://localhost:2034
      base-url: /interoperation/v1
      quotes-path: ${ams.local.interop.base-url}/quotes
      parties-path: ${ams.local.interop.base-url}/parties/{idType}/{idValue}
      transfers-path: ${ams.local.interop.base-url}/transfers
    customer:
      host: http://localhost:2024
      base-url: /customer/v1
      path: ${ams.local.customer.base-url}/customers/{customerIdentifier}
    account:
      host: http://localhost:2027
      base-url: /deposit/v1
      path: ${ams.local.account.base-url}/instances/{accountId}
    auth:
      host: http://localhost:2021
      base-url: /identity/v1
      path: ${ams.local.auth.base-url}/token
